### ISSUE TITLE
is this library supports blurring selected portions of image like instagram does?

### ISSUE THREAD

**Issue by karthikeyanvijayan** [OmidH/Filtrr#1]
Hii ,

Thanks for this awesome and lightweight library,

i m trying to implement a blurring feature like selected portion of image will gets blurred ?

currently i m writing custom methods to handle it , is any blurring feature it supports?

Thanks once again.

**Comment by OmidH** [comment]
Hi Karthikeyan,

at the moment their is no such functionality for partwise selection of image areas to run a filter on it. 
If you have such code - maybe you could send it to me as PM and I will add it to the lib :)

kr,

Omid

**Comment by zuil7** [comment]
Hi,
      Thanks for sharing this awesome library filter. Just want to asked if we could make the applying filter more faster. I have notice that it takes time for the filter to take effect on the photo. Is there a way to make it more faster?

Thanks!
