### ISSUE TITLE
Use ActivityIndicator For Processing New Image 

### ISSUE THREAD

**Issue by rushabh0999** [OmidH/Filtrr#4]
Hi,

First Of All Thanks a Lot s For Sharing Cool Image Filter .........its Awesome 

I want to use the Activity Indicator for when Processing the image Filter after Returning the New filter image Then after the

activity indicator stop ...

Thanks in Advance ............

**Comment by OmidH** [comment]
You can do this, the way I track time. See UIImage+FiltrrCompositions.m -> -(id) trackTime:(NSString *)method;
