### ISSUE TITLE
Not work with iPhone 6 simulator

### ISSUE THREAD

**Issue by JasonHuang** [OmidH/Filtrr#6]
Hi, Omid Hashemi

Thanks for your effort for the amazing library, but lately I 'm trying to run my app on iPhone 6 simulator, It halt with a EXEC_BAD_ACCESS on this line

```
        outData[outIndex]     = [self safe:r];
```

any hint help me work through this?

many thanks

Jason.

**Comment by OmidH** [comment]
I'm sorry I won't be able to respond to you for at least two week as I am in vacation. I will respond once I have returned and recovered.

Thanks in advance,

Omid Hashemi

**Comment by ChoiBongKyu** [comment]
Blocked from this problem too difficult.
People to be worried and I'll teach you.

unsigned char \* data = malloc (_height \* _width \* 4);

Under part

            data [outIndex] = [self safe: r];
            data [outIndex + 1] = [self safe: g];
            data [outIndex + 2] = [self safe: b];
            data [outIndex + 3] = 255;
        }
    }
    
    return data;

So after I fix the build.

**Comment by sprite2005** [comment]
Fix:

-(id) convolve:(NSArray *) kernel {

```
CGContextRef cgctx = [self createARGBBitmapContextFromImage:self.CGImage];
size_t _width = CGImageGetWidth(self.CGImage);
size_t _height = CGImageGetHeight(self.CGImage);

unsigned char* inData = CGBitmapContextGetData (cgctx);
NSData* pixelData = (__bridge NSData*) CGDataProviderCopyData(CGImageGetDataProvider(self.CGImage));
NSMutableData* mutablePixelData = [pixelData mutableCopy];
//unsigned char* outData = (unsigned char*)[pixelData bytes];
unsigned char* outData = (unsigned char*)[mutablePixelData mutableBytes];

outData = [self convolveRaw:kernel InData:inData OuData:outData Height:_height Width:_width];

UIImage *newImage = [self createImageFromPixels:outData Length:pixelData.length];
```

//    if(outData) free(outData);
    if(inData) free(inData);

```
return newImage;
```

}

**Comment by darkmeton** [comment]
Tried both methods. The second one by sprite2005 seemed to work better. Thank you. You should probably update the code in the repo

**Comment by OmidH** [comment]
The code is now updated. Thank you to all of you!
